### ISSUE TITLE
aws-sdk promise tip

### ISSUE THREAD

**Issue by felimartina** [jbesw/askJames-serverlessCrawler#1]
Hey! I just came across your post in acloud.guru! nice read.

By looking at your code I couldn't stop noticing that you are wrapping `aws-sdk` calls (like dynamodb) in a promise like the following:
```
return new Promise((resolve, reject) => {
  ddb.batchWriteItem(batchParams, function (err, data) {
  ...
  });
});
```

Did you know that `aws-sdk` has native support for promises?
You could simply use:
```
return ddb.batchWriteItem(batchParams).promise()
```

Anyway! Great read and project.

Cheers!

**Comment by jbesw** [comment]
Good point! I will update in the next review. Thanks for the tip!
